/*PIPELINED FUNCTION

TABLE FUNCTION LOAD ALL THE VALUES INTO COLLECTION AND FINALLY THE COLLECTION WOULD BE RETURNED TO CALLER.
PIPELINED FUNCTION RETURN THE VALUES AS AND WHEN THE VALUE IS READY TO SEND BACK CALLER OR IT ALLOW THE ROWS TO BE RETURNED ONE AT A TIME,IMPROVING PERFORMANCE 
WHEN WORKING WITH LARGE DATASET.

*/

CREATE OR REPLACE TYPE
T_EMP_LIST IS TABLE OF VARCHAR2(30);


CREATE OR REPLACE FUNCTION FN_GET_EMP_NAME_LIST 
RETURN T_EMP_LIST PIPELINED AS --PIPELINED KEYWORD INDICATES THAT THE FUNCTION WILL RETURN ROW ITERATIVELY.
LV_EMP_LIST T_EMP_LIST:=T_EMP_LIST();

BEGIN
    FOR I IN(SELECT EMP_NAME FROM EMP)
    LOOP
        PIPE ROW(I.EMP_NAME);--THIS STATEMENT CAUSES A TABLE FUNCTION TO PIP A ROW AND CONTINUE PROCESSING.
    END LOOP;
    RETURN;--A PIPELINED TABLE FUNCTION MUST HAVE A RETURN STATEMENT THAT DOES NOT RETURN A VALUE.
END;
  

SELECT * FROM (FN_GET_EMP_NAME_LIST()) WHERE ROWNUM<=3;

EXPLAINATION:
PIPELINED : ALLOW FUNCTION TO RETURN ROW ONE BY ONE,INSTEAD OF RETURNING THE ENTIRE COLLECTION AT ONCE.
PIPE : RETURN A SINGLE ROW TO THE CALLING QUERY

USE CASE:
1.DATA NEED TO BE RETRIVED INCREMENTLY(USING PIPELINED TABLE FUNCTIONS)
2.YOU NEED TO RETURN DYNAMIC ,COMPUTED SETS OF ROWS.
