IN ORACLE RECORD AND COLLECTIONS ARE BOTH TYPE OF PL/SQL DATA STRUCTURE USED FOR STORING AND MANIPULATING SET OF DATA.
THEY ARE OFTEN USED TOGETHER TO CREATE POWERFUL STRUCTURES THAT MODELS COMPLEX DATA RELATIONSHIPS.

A COLLECTION IS AN ORDERED GROUP OF LOGICALLY RELATED ELEMENT.
In Oracle SQL, collections are data structures that allow you to store multiple values of the same data type,
similar to arrays in other programming languages. Oracle provides three main types of collections:

Associative Arrays (Index-by Tables):
Nested Tables
VARRAY (Variable size array)
    
-LIST OF EMPLOYEE NAME
-ADDRESS OF EMPLOYEE

- IN COLLECTION THE INTERNAL COMPONENTS ALWAYS HAVE THE SAME DATA TYPE AND ARE CALLED ELEMENTS. 
- A COLLECTION IS A SET OF ELEMENTS OF THE SAME TYPE,SUCH AS ARRAY,LIST OR TABLE.

RECORDS
-IN A RECORD,THE INTERNAL COMPONENT HAVE DIFFERENT DATA  TYPE CALLED FIELD.
-A RECORD IN PL/SQL IS SIMILAR TO A ROW IN A TABLE CONTAINING FIELDS WITH VARIOUS DATA TYPES.    



DATA TYPES

1.SCALAR DATA TYPES
    1.1 NUMERIC DATA TYPE (NUMBER,INTEGER ETC.)
    1.2 STRING DATA TYPE (CHAR,VARCHAR,VARCHAR2,NCHAR,NVARCHAR2)
    1.3 BOOLEAN
    1.4 LARGE FILE(BLOB,CLOB,NCLOB)
    1.5 DATE,TIMESTAMP
    
2.COMPOSITE DATA TYPES
    2.1 RECORD
        2.1.1 TYPE
        2.1.2 %ROWTYPE
        
    2.2 COLLECTION
        2.2.1 VARRAY
        2.2.2 NESTED TABLE
        2.2.3 ASSOCIATIVE ARRAY
        
3.REFERENCE TYPES
    3.1 REF CURSOR
